language: csharp
sudo: required
mono: none
dotnet: 1.0.4
dist: trusty
addons:
  apt:
    packages:
      - docker-ce
before_script: npm install -g markdownlint-cli
script:
  - markdownlint .
  - dotnet restore
  - dotnet build -c Release
  - dotnet vstest ./test/Contentment.Api.Test/bin/Release/netcoreapp1.1/Contentment.Api.Test.dll ./test/Contentment.Api.IntegrationTest/bin/Release/netcoreapp1.1/Contentment.Api.IntegrationTest.dll
  - if [[ $TRAVIS_PULL_REQUEST == “false” ]] && [[ $TRAVIS_BRANCH == “master” ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      cd src/Contentment.Api/;
      export SLUG=contentmentcms/contentment.api:0.0.1.$TRAVIS_JOB_ID;
      docker build -t $SLUG --build-arg BUILD_NUMBER=$TRAVIS_JOB_ID .;
      docker push $SLUG;
    fi

services:
  - docker